AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline for Inventory Microservice

Resources:
  InventoryPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: "{{resolve:ssm:/inventory/dev/pipeline-role-arn}}"
      Stages:
        - Name: Source
          Actions:
            - Name: InventorySource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              Configuration:
                RepositoryName: "{{resolve:ssm:/inventory/dev/service-name}}"
                BranchName: "main"
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Build
          Actions:
            - Name: InventoryBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: "build-inventory-service"
