AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline for Loyalty Microservice

Resources:
  LoyaltyPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: "{{resolve:ssm:/loyalty/dev/pipeline-role-arn}}"
      Stages:
        - Name: Source
          Actions:
            - Name: LoyaltySource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              Configuration:
                RepositoryName: "{{resolve:ssm:/loyalty/dev/service-name}}"
                BranchName: "main"
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Build
          Actions:
            - Name: LoyaltyBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: "build-loyalty-service"
