AWSTemplateFormatVersion: '2010-09-09'
Description: Smart Hotel Booking - ECS Cluster

Parameters:
  EnvironmentName:
    Type: String
    Default: dev

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${EnvironmentName}-ecs-cluster"

Outputs:
  ECSClusterName:
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${EnvironmentName}-ecs-cluster"
