AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline for ECS-based service

Parameters:
  EnvironmentName:
    Type: String
  ServiceName:
    Type: String
  ArtifactBucket:
    Type: String
  SourceRepo:
    Type: String
  BranchName:
    Type: String
  PipelineRoleArn:
    Type: String
    Description: IAM role ARN for CodePipeline service execution

Resources:
  ServicePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${ServiceName}-${EnvironmentName}-pipeline"
      RoleArn: !Ref PipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: !Ref SourceRepo
                BranchName: !Ref BranchName
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Sub "${ServiceName}-${EnvironmentName}-build"

