AWSTemplateFormatVersion: '2010-09-09'
Description: Step Function for Invoice Generation

Parameters:
  GenerateInvoiceLambdaArn:
    Type: String

Resources:
  InvoiceStepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: arn:aws:iam::<ACCOUNT_ID>:role/StepFunctionExecutionRole
      DefinitionString:
        !Sub
          - |
            {
              "StartAt": "GenerateInvoice",
              "States": {
                "GenerateInvoice": {
                  "Type": "Task",
                  "Resource": "${GenerateInvoiceLambdaArn}",
                  "End": true
                }
              }
            }
          - GenerateInvoiceLambdaArn: !Ref GenerateInvoiceLambdaArn
