AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to generate invoice

Resources:
  GenerateInvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: generate-invoice
      Handler: handler.lambda_handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /generate-invoice
            Method: post
