AWSTemplateFormatVersion: '2010-09-09'
Description: Smart Hotel Booking - CI/CD Pipeline for Microservices

Parameters:
  GitHubOwner:
    Type: String
  GitHubRepo:
    Type: String
  GitHubBranch:
    Type: String
  GitHubOAuthToken:
    Type: String

Resources:
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: smart-hotel-codepipeline-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Sub "${AWS::AccountId}-codepipeline-artifacts"
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: smart-hotel-codebuild-project
              RunOrder: 1

        - Name: DeployAuth
          Actions:
            - Name: DeployAuthStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: smart-hotel-auth
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: BuildOutput::cfn/env-dev/pipeline.yml
                ParameterOverrides: |
                  {
                    "ServiceName": "auth",
                    "ContainerPort": "5000",
                    "ContainerImage": "REPLACE_WITH_ECR_URL/auth:latest",
                    "EnvironmentName": "dev"
                  }
              RunOrder: 1

        - Name: DeployBooking
          Actions:
            - Name: DeployBookingStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: smart-hotel-booking
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: BuildOutput::cfn/env-dev/pipeline.yml
                ParameterOverrides: |
                  {
                    "ServiceName": "booking",
                    "ContainerPort": "5001",
                    "ContainerImage": "REPLACE_WITH_ECR_URL/booking:latest",
                    "EnvironmentName": "dev"
                  }
              RunOrder: 1

        - Name: DeployLoyalty
          Actions:
            - Name: DeployLoyaltyStack
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: smart-hotel-loyalty
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: BuildOutput::cfn/env-dev/pipeline.yml
                ParameterOverrides: |
                  {
                    "ServiceName": "loyalty",
                    "ContainerPort": "5002",
                    "ContainerImage": "REPLACE_WITH_ECR_URL/loyalty:latest",
                    "EnvironmentName": "dev"
                  }
              RunOrder: 1
